import {todoService} from "../core/todoService.mjs";


const eventListsChanged = () => {
    document.dispatchEvent(new CustomEvent("custom:listsChanged"));
}


$(() => {
    // It is the same as $(document).ready(function() { ... });
    // This block will be executed once the page has been loaded
    // Some kind of unnecessary code, when the script tag is at the end of the body

    if (!todoService.lists.length) {
        for (let i = 0; i < 5; i++) {
            todoService.createList(
                "Testing list",
                "Generated by script.js if there are no lists"
            );
        }
        eventListsChanged();
    }

    renderLists();
    document.addEventListener('custom:listsChanged', renderLists);
})


const renderLists = () => {
    const $lists = $("#lists");
    $lists.empty();

    if (!todoService.lists.length) {
        $lists.append(`
            <div class="no-lists">
                <h3 class="list-name">No lists</h3>
                <p class="list-description">Create a new list</p>
            </div>
        `);
        return;
    }

    todoService.lists.forEach(list => {
        const $list = $(`
            <div class="list">
                <h3 class="list-name">${list.name}</h3>
                <p class="list-description">${list.description}</p>
                <div class="list-actions">
                    <a href="../list/index.html?listId=${list.id}">
                        <button class="btn btn-primary">Open</button>
                    </a>
                    <button class="btn btn-danger">Delete</button>
                </div>
            </div>
        `);

        $list.find('.btn-danger').click(() => {
            todoService.deleteList(list.id);
            eventListsChanged();
        });

        $("#lists").append($list);
    });
}
